// data/heritage-classified.geojson → backend/src/data/heritageSites.generated.ts
// /api/sites 가 서빙할 "필요한 필드만 추린" 유산 목록을 만든다. 생성 결과는 커밋 대상이다
// (원본 geojson 은 용량 때문에 커밋하지 않으므로, 배포되는 백엔드는 이 파일만 본다).
//
// 필드: id, name, region, sigungu, material, heritageType, lat, lng, regionTag, elevationProfile, (era, desc)
//  - id            유산코드(17자리 문자열, 전국 유일)
//  - region        시도명 축약형("경상북도"→"경북"). 기존 mock 16곳의 표기 관례와 맞춘다
//  - sigungu       원본 시군구명 그대로 (수동 매핑 없음). 원본에 비어 있는 1건은 생략
//  - heritageType  원본 종목명 (국보·보물·사적·국가민속문화유산)
//  - lat, lng      원본 대표점(polylabel) 소수 5자리(≈1m)
//  - regionTag / elevationProfile
//                  기존 mock 16곳에 대응하는 레코드는 sites.mock.ts 의 현재 값을 그대로 물려받고(era·desc 포함),
//                  나머지는 기본값 regionTag "plain" / elevationProfile "plain"(지형 보정 없음)
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const IN_FILE = path.join(ROOT, "data/heritage-classified.geojson");
const MOCK_FILE = path.join(ROOT, "frontend/src/data/sites.mock.ts");
const OUT_FILE = path.join(ROOT, "backend/src/data/heritageSites.generated.ts");

const REGION_SHORT = {
  서울특별시: "서울", 부산광역시: "부산", 대구광역시: "대구", 인천광역시: "인천", 광주광역시: "광주", 대전광역시: "대전", 울산광역시: "울산",
  세종특별자치시: "세종", 경기도: "경기", 강원특별자치도: "강원", 충청북도: "충북", 충청남도: "충남", 전북특별자치도: "전북", 전라남도: "전남",
  전남광주통합특별시: "전남광주", 경상북도: "경북", 경상남도: "경남", 제주특별자치도: "제주",
};

// 기존 mock 16곳 ↔ 데이터셋 레코드(유산코드). 이름을 함께 적어 두고 빌드 때 일치하는지 검사한다.
const MOCK_LINKS = {
  bulguksa: ["13000502000000037", "경주 불국사"],
  seokguram: ["11000024000000037", "경주 석굴암 석굴"],
  cheomseongdae: ["11000031000000037", "경주 첨성대"],
  buseoksa: ["11000018000000037", "영주 부석사 무량수전"],
  hahoe: ["18000122000000037", "안동 하회마을"],
  haeinsa: ["11000052000000038", "합천 해인사 장경판전"],
  namhansanseong: ["13000057000000031", "남한산성"],
  hwaseong: ["13000003000000031", "수원 화성"],
  jongmyo: ["11000227000000011", "종묘 정전"],
  huwon: ["13000122000000011", "창덕궁"],
  gongsanseong: ["13000012000000034", "공주 공산성"],
  muryeongneung: ["13000013000000034", "공주 무령왕릉과 왕릉원"],
  jeongnimsaji: ["11000009000000034", "부여 정림사지 오층석탑"],
  mireuksaji: ["11000011000000035", "익산 미륵사지 석탑"],
  hwasundolmen: ["13000410000000036", "화순 효산리와 대신리 지석묘군"],
  ganghwadolmen: ["13000137000000023", "강화 부근리 지석묘"],
};

// sites.mock.ts 한 줄에서 id/regionTag/elevationProfile/era/desc 를 읽는다 (값을 이 스크립트에 복사해 두면 어긋날 수 있으므로 원본을 직접 파싱)
function readMock() {
  const out = {};
  const re = /\{ id: "(\w+)",.*?regionTag: "([\w-]+)", elevationProfile: "([\w-]+)", era: "([^"]*)",.*?desc: "([^"]*)" \}/;
  for (const line of fs.readFileSync(MOCK_FILE, "utf8").split(/\r?\n/)) {
    const m = line.match(re);
    if (m) out[m[1]] = { regionTag: m[2], elevationProfile: m[3], era: m[4], desc: m[5] };
  }
  return out;
}

const mock = readMock();
const mockIds = Object.keys(MOCK_LINKS);
const missing = mockIds.filter((id) => !mock[id]);
if (missing.length || Object.keys(mock).length !== mockIds.length) throw new Error(`mock 파싱/링크 불일치: 누락 ${missing.join(",")} / mock ${Object.keys(mock).length}개`);
const linkByCode = new Map(mockIds.map((id) => [MOCK_LINKS[id][0], id]));

const features = JSON.parse(fs.readFileSync(IN_FILE, "utf8")).features;
const round5 = (v) => Math.round(v * 1e5) / 1e5;
const records = [];
const seen = new Set();

for (const f of features) {
  const p = f.properties;
  const region = REGION_SHORT[p.시도명];
  if (!region) throw new Error(`알 수 없는 시도명: ${p.시도명} (${p.국가유산명})`);
  if (seen.has(p.유산코드)) throw new Error(`유산코드 중복: ${p.유산코드}`);
  seen.add(p.유산코드);

  const mockId = linkByCode.get(p.유산코드);
  if (mockId && MOCK_LINKS[mockId][1] !== p.국가유산명) throw new Error(`링크 이름 불일치: ${mockId} → ${p.국가유산명} (기대 ${MOCK_LINKS[mockId][1]})`);
  const m = mockId ? mock[mockId] : null;

  const rec = { id: p.유산코드, name: p.국가유산명, region };
  if (p.시군구명) rec.sigungu = p.시군구명;
  Object.assign(rec, { material: p._material, heritageType: p.종목명, lat: round5(p._repLat), lng: round5(p._repLng), regionTag: m?.regionTag ?? "plain", elevationProfile: m?.elevationProfile ?? "plain" });
  if (m) { rec.era = m.era; rec.desc = m.desc; }
  records.push(rec);
}
const linked = records.filter((r) => r.era);
if (linked.length !== mockIds.length) throw new Error(`mock 연결 ${linked.length}건 (기대 ${mockIds.length})`);

records.sort((a, b) => (a.id < b.id ? -1 : 1));
const header = `// AUTO-GENERATED by scripts/heritage/build-sites.mjs from data/heritage-classified.geojson — 직접 수정하지 말고 스크립트를 다시 실행할 것.
// ${records.length}건. regionTag/elevationProfile 은 mock 16곳 대응 레코드만 실제 값, 나머지는 기본값("plain").
import type { SiteRecord } from "./siteRecord";

export const HERITAGE_SITES: SiteRecord[] = [
`;
const tmp = OUT_FILE + ".part";
fs.writeFileSync(tmp, header + records.map((r) => JSON.stringify(r)).join(",\n") + "\n];\n");
fs.renameSync(tmp, OUT_FILE);

const tally = (get) => records.reduce((o, r) => ((o[get(r)] = (o[get(r)] ?? 0) + 1), o), {});
console.log(`생성: ${records.length}건 → ${path.relative(ROOT, OUT_FILE)} (${(fs.statSync(OUT_FILE).size / 1024).toFixed(0)}KB)`);
console.log("재질:", JSON.stringify(tally((r) => r.material)));
console.log("regionTag:", JSON.stringify(tally((r) => r.regionTag)), "| elevationProfile:", JSON.stringify(tally((r) => r.elevationProfile)));
console.log(`sigungu 없음 ${records.filter((r) => !r.sigungu).length}건, mock 연결 ${linked.length}건`);
